### ISSUE TITLE
HTTP Error 403 when downloading weights

### ISSUE THREAD

**Issue by ArnNag** [HeliXonProtein/OmegaFold#4]
I am trying to run main.py and it is failing to download the weights from https://helixon.s3.amazonaws.com/release1.pt . Using wget also gave me a 403 error.

**Comment by josemduarte** [comment]
I'm seeing the same issue too. 403 with either `main.py` or `curl`.

**Comment by dzyla** [comment]
Same here. 

`INFO:root:Downloading weights from https://helixon.s3.amazonaws.com/release1.pt to /home/gpu/.cache/omegafold_ckpt/model.pt
Traceback (most recent call last):
  File "/mnt/staging/Dawid/OmegaFold/main.py", line 105, in <module>
    main()
  File "/home/gpu/miniconda3/envs/omegafold/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/staging/Dawid/OmegaFold/main.py", line 42, in main
    args, state_dict, forward_config = pipeline.get_args()
  File "/mnt/staging/Dawid/OmegaFold/pipeline.py", line 346, in get_args
    weights = _load_weights(weights_url, weights_file)
  File "/mnt/staging/Dawid/OmegaFold/pipeline.py", line 248, in _load_weights
    hub.download_url_to_file(weights_url, weights_file)
  File "/home/gpu/miniconda3/envs/omegafold/lib/python3.10/site-packages/torch/hub.py", line 593, in download_url_to_file
    u = urlopen(req)
  File "/home/gpu/miniconda3/envs/omegafold/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/home/gpu/miniconda3/envs/omegafold/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/home/gpu/miniconda3/envs/omegafold/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/home/gpu/miniconda3/envs/omegafold/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/home/gpu/miniconda3/envs/omegafold/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/gpu/miniconda3/envs/omegafold/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
`

**Comment by RuiWang1998** [comment]
Sorry for the inconvenience, we had a couple of permission problems with AWS and will be resolved very soon!

**Comment by RuiWang1998** [comment]
Hi all, 

It appears we have dealt with the issue and the weights are downloadable now. Please try again when you can and we are going to close this issue for now!

**Comment by dzyla** [comment]
I can confirm that the download works! Thank you!
