### ISSUE TITLE
Exception: Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] is not supported.

### ISSUE THREAD

**Issue by Herutriana44** [HeliXonProtein/OmegaFold#69]
i get error when build omegafold using python 3.11.4

`Traceback (most recent call last):
  File "C:\Users\herutriana44\omagafold\OmegaFold\setup.py", line 35, in <module>
    f"torch@{get_url()}"
             ^^^^^^^^^
  File "C:\Users\herutriana44\omagafold\OmegaFold\setup.py", line 15, in get_url
    raise Exception(f"Python {sys.version} is not supported.")
Exception: Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] is not supported.`

how to solved this problem?

**Comment by lwhitm1** [comment]
Were you able to figure this out? When I try to build I get a similar error for python 3.11.7 and 3.11.8.

```
Traceback (most recent call last):
  File "/projects/liwh2139/software/OmegaFold/setup.py", line 35, in <module>
    f"torch@{get_url()}"
             ^^^^^^^^^
  File "/projects/liwh2139/software/OmegaFold/setup.py", line 15, in get_url
    raise Exception(f"Python {sys.version} is not supported.")
Exception: Python 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:53:32) [GCC 12.3.0] is not supported.
```

**Comment by Herutriana44** [comment]
This issued haven't clear, i haven't get any solutions.

**Comment by alexrunqin** [comment]
It's because of the way the code is written it only supports python versions 3.8, 3.9, and 3.10.
![image](https://github.com/HeliXonProtein/OmegaFold/assets/68905097/f2b838c8-99c9-4047-a6ff-1a45ec7db07a)

**Comment by Herutriana44** [comment]
> It's because of the way the code is written it only supports python versions 3.8, 3.9, and 3.10. ![image](https://private-user-images.githubusercontent.com/68905097/328737335-f2b838c8-99c9-4047-a6ff-1a45ec7db07a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMzc5OTcsIm5iZiI6MTcxNTEzNzY5NywicGF0aCI6Ii82ODkwNTA5Ny8zMjg3MzczMzUtZjJiODM4YzgtOTljOS00MDQ3LWE2ZmYtMWE0NWVjN2RiMDdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDAzMDgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjODE0OWU1ZWI3ZmQ3ODMwMjIwODQ5M2U5MjllNmVhNmI5NWI4MzQyODMzMzUxYTA1NDkzZTMzMjU3ZTYzOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mYgljRyScOy-7HZH6euxmsBTvV5FGoM8yQ0csryU9to)

I see, thanks for your information.

**Comment by Hlunlun** [comment]
So can we change the version?

**Comment by RoseTCHALA** [comment]
I had the same issue. what i did is changing the source code to 
def get_url() -> str:
    if sys.version_info[:2] == (3, 8):
        _ver = "cp38"
    elif sys.version_info[:2] == (3, 9):
        _ver = "cp39"
    elif sys.version_info[:2] == (3, 10):
        _ver = "cp310"
    else:
        #raise Exception(f"Python {sys.version} is not supported.")
        _ver = "cp310"
and it worked

**Comment by fnachon** [comment]
Alternatively, you can remove that piece of code in setup.py that is to download and install pytorch:
```
def get_url() -> str:
    if sys.version_info[:2] == (3, 8):
        _ver = "cp38"
    elif sys.version_info[:2] == (3, 9):
        _ver = "cp39"
    elif sys.version_info[:2] == (3, 10):
        _ver = "cp310"
    else:
        raise Exception(f"Python {sys.version} is not supported.")

    # FIXME: how to download on macox??
    if sys.platform == "win32":
        _os = "win_amd64"
    else:
        _os = "linux_x86_64"

    return f"https://download.pytorch.org/whl/cu113/torch-1.12.0%2Bcu113-{_ver}-{_ver}-{_os}.whl"
```
And create a specific conda environment for installing pytorch. There is no problem with PyTorch 2.6.0
