### ISSUE TITLE
Unable to run setup.py on M1 Mac

### ISSUE THREAD

**Issue by rofessori** [HeliXonProtein/OmegaFold#77]
Trying to run the setup.py results the error:

Traceback (most recent call last):
  File "...../OmegaFold/setup.py", line 35, in <module>
    f"torch@{get_url()}"
             ~~~~~~~^^
  File "...../OmegaFold/setup.py", line 15, in get_url
    raise Exception(f"Python {sys.version} is not supported.")
Exception: Python 3.13.0 (main, Oct  7 2024, 05:02:14) [Clang 16.0.0 (clang-1600.0.26.3)] is not supported.

What should I do?

**Comment by fnachon** [comment]
Hello, it is an easy fix.
The setup.py script is designed to find and install a version of PyTorch that is compatible with Omegafold.

But you do not need it if you use conda environment.

So first, create a conda environment with the last version of python
`conda create --name omegafold python=3.13`
then `conda activate omegafold`
Install the required dependencies with conda
`conda install -c conda-forge pytorch biopython`

Edit the setup.py script as follow:
```
from setuptools import setup, find_packages
import sys

with open("README.md", "r") as f:
    readme = f.read()

setup(
    name="OmegaFold",
    description="OmegaFold Release Code",
    long_description=readme,
    long_description_content_type="text/markdown",
    license="Apache-2.0",
    packages=find_packages(exclude=["tests", "tests.*"]),
    entry_points={"console_scripts": ["omegafold=omegafold.__main__:main",],},
    install_requires=[
        "biopython"
    ],
    python_requires=">=3.8",
)
```
and run the script to complete the installation
`python setup.py install`

and test it:
`omegafold yourfastafile.fasta resultsfolder`
